require ("thrashdev.launch")
require ("thrashdev.options")
require ("thrashdev.keymaps")
spec ("thrashdev.colorscheme")
spec ("thrashdev.devicons")
spec ("thrashdev.treesitter")
spec ("thrashdev.mason")
spec ("thrashdev.whichkey")
spec ("thrashdev.lspconfig")
spec ("thrashdev.cmp")
-- spec ("thrashdev.none-ls")
require ("thrashdev.lazy")

